version: 2

sources:

  - name: raw
    schema: gz_raw_data
    description: dataset greenwiz
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: détail des commandes et produits vendus
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
              warn_after: {count: 90, period: day }
        columns:
          - name: date_date
            description: date
          - name: orders_id
            description: numéro de commande
          - name: pdt_id
            description:  identifiant produit
          - name: revenue
            description: revenue sur ce produit
          - name: quantity
            description: nombre d'exemplaire achetés du même article
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)" 
      - name: product
        identifier: raw_gz_product
        description: prix de chaque produit
        columns:
          - name: products_id
            description: identifiant produit
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: prix d'achat 
      - name: ship
        identifier: raw_gz_ship
        description: coûts de chaque commande
        columns:
          - name: orders_id
            description: numéro de commande
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: frais de livraison
          - name: logCost
            description: coût logistique
          - name: ship_cost
            description: coût livraison
      - name: adwords
        identifier: raw_gz_adwords
        description: détails campagne adwords
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: source
          - name: campaign_key
            description: id de la campagne
          - name: camPGN_name
            description: nom campagne pub
          - name: ads_cost
            description: daily cost
          - name: impression
            description: nb impressions
          - name: click
            description: nb clicks
      - name: bing
        identifier: raw_gz_bing
        description: détails campagne bing
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: source
          - name: campaign_key
            description: id de la campagne
          - name: camPGN_name
            description: nom campagne pub
          - name: ads_cost
            description: daily cost
          - name: impression
            description: nb impressions
          - name: click
            description: nb clicks
      - name: criteo
        identifier: raw_gz_criteo
        description: détails campagne criteo
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: source
          - name: campaign_key
            description: id de la campagne
          - name: camPGN_name
            description: nom campagne pub
          - name: ads_cost
            description: daily cost
          - name: impression
            description: nb impressions
          - name: click
            description: nb clicks
      - name: facebook
        identifier: raw_gz_facebook
        description: détails campagne facebook
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: source
          - name: campaign_key
            description: id de la campagne
          - name: camPGN_name
            description: nom campagne pub
          - name: ads_cost
            description: daily cost
          - name: impression
            description: nb impressions
          - name: click
            description: nb clicks
models:
      - name: int_campaigns
        description: all campaigns aggrégées 
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: source
          - name: campaign_key
            description: id de la campagne
          - name: camPGN_name
            description: nom campagne pub
          - name: ads_cost
            description: daily cost
          - name: impression
            description: nb impressions
          - name: click
            description: nb clicks
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"